### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by knownasilya** [alexlafroscia/ember-iframe-resizer-modifier#41]
Looks like ember-modifier was updated, which addresses https://discuss.emberjs.com/t/setsourcedestroyed-with-ember-3-20/18100/3. Any chance you could cut a new release?

**Comment by alexlafroscia** [comment]
Done! `v1.0.2` released

**Comment by alexlafroscia** [comment]
It seems like `1.0.1`, which was released about 3 weeks ago, also included `ember-modifier@2.1.0`. Is there a newer version than that that you were looking for?
