### ISSUE TITLE
Release new version due to bump of ember-auto-import to 2.x?

### ISSUE THREAD

**Issue by ryanone** [alexlafroscia/ember-iframe-resizer-modifier#507]
I'd like to ask if you're planning on releasing a new major version of this package due to the upgrade of ember-auto-import to 2.x, as outlined in the [Quick Summary section](https://github.com/ef4/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md#quick-summary) of the ember-auto-import upgrade guide? Thanks!

**Comment by alexlafroscia** [comment]
`2.0.0` was just released from `master`, so it should contain the upgrade of `ember-auto-import` to version 2 👍
